package tcm.xxmst.basic.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "xxmst_students_details")
public class StudentsDetails extends BaseDTO {

    public static final String FIELD_STUDENT_ID = "studentId";
    public static final String FIELD_STUDENT_TYPE = "studentType";
    public static final String FIELD_STUDENT_NUM = "studentNum";
    public static final String FIELD_STUDENT_NAME = "studentName";
    public static final String FIELD_VIP_LEVEL = "vipLevel";
    public static final String FIELD_BORN_DATE = "bornDate";
    public static final String FIELD_JOIN_DATE = "joinDate";
    public static final String FIELD_ADDRESS = "address";
    public static final String FIELD_MOBILE = "mobile";
    public static final String FIELD_PARENT_NAME = "parentName";
    public static final String FIELD_PARENT_MOBILE = "parentMobile";
    public static final String FIELD_COMMENTS = "comments";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Id
    @GeneratedValue
    private Long studentId; //表ID，主键，供其他表做外键

    @NotEmpty
    @Length(max = 30)
    private String studentType; //类型

    @Condition(
            operator = "LIKE"
    )
    @Length(max = 30)
    private String studentNum; //编号

    @Condition(
            operator = "LIKE"
    )
    @Length(max = 100)
    private String studentName; //姓名

    @Length(max = 30)
    private String vipLevel; //VIP级别

    private Date bornDate; //生日

    private Date joinDate; //加入日期

    @Length(max = 240)
    private String address; //住址

    @Length(max = 100)
    private String mobile; //电话

    @Condition(
            operator = "LIKE"
    )
    @Length(max = 240)
    private String parentName; //父母信息

    @Length(max = 240)
    private String parentMobile; //父母联系电话

    @Length(max = 4000)
    private String comments; //备注

    private String gender;

    private Long programApplicationId;

    private Date programUpdateDate;
    @Transient
    private Long attendCount;


    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    public Long getStudentId() {
        return studentId;
    }

    public void setStudentType(String studentType) {
        this.studentType = studentType;
    }

    public String getStudentType() {
        return studentType;
    }

    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum;
    }

    public String getStudentNum() {
        return studentNum;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public String getStudentName() {
        return studentName;
    }

    public void setVipLevel(String vipLevel) {
        this.vipLevel = vipLevel;
    }

    public String getVipLevel() {
        return vipLevel;
    }

    public void setBornDate(Date bornDate) {
        this.bornDate = bornDate;
    }

    public Date getBornDate() {
        return bornDate;
    }

    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    public Date getJoinDate() {
        return joinDate;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress() {
        return address;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getMobile() {
        return mobile;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentMobile(String parentMobile) {
        this.parentMobile = parentMobile;
    }

    public String getParentMobile() {
        return parentMobile;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getComments() {
        return comments;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Long getAttendCount() {
        return attendCount;
    }

    public void setAttendCount(Long attendCount) {
        this.attendCount = attendCount;
    }
}
