package tcm.xxmst.basic.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "xxmst_teachers_details")
public class TeachersDetails extends BaseDTO {

     public static final String FIELD_TEACHER_ID = "teacherId";
     public static final String FIELD_TECH_TYPE = "techType";
     public static final String FIELD_EDUCATION_TYPE = "educationType";
     public static final String FIELD_EDUCATION_SCHOOL = "educationSchool";
     public static final String FIELD_GRADURATION_DATE = "gradurationDate";
     public static final String FIELD_TEACHER_NUM = "teacherNum";
     public static final String FIELD_TEACHER_NAME = "teacherName";
     public static final String FIELD_BORN_DATE = "bornDate";
     public static final String FIELD_EMAIL = "email";
     public static final String FIELD_MOBILE = "mobile";
     public static final String FIELD_JOIN_DATE = "joinDate";
     public static final String FIELD_GENDER = "gender";
     public static final String FIELD_CERTIFICATE_TYPE = "certificateType";
     public static final String FIELD_CERTIFICATE_ID = "certificateId";
     public static final String FIELD_EFFECTIVE_START_DATE = "effectiveStartDate";
     public static final String FIELD_EFFECTIVE_END_DATE = "effectiveEndDate";
     public static final String FIELD_BANK_ACCOUNT = "bankAccount";
     public static final String FIELD_BANK_NAME = "bankName";
     public static final String FIELD_BANK_BRANCH_NAME = "bankBranchName";
     public static final String FIELD_COMMENTS = "comments";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long teacherId; //表ID，主键，供其他表做外键

     @NotEmpty
     @Length(max = 30)
     private String techType; //教师类型

     @Length(max = 30)
     private String educationType; //最高学历

     @Length(max = 100)
     private String educationSchool; //毕业学校

     private Date gradurationDate; //毕业时间

     @NotEmpty
     @Length(max = 30)
     private String teacherNum; //编号

     @NotEmpty
     @Length(max = 100)
     private String teacherName; //姓名

     private Date bornDate; //生日

     @Length(max = 100)
     private String email; //邮箱

     @Length(max = 100)
     private String mobile; //手机

     private Date joinDate; //入职日期

     @Length(max = 10)
     private String gender; //性别

     @Length(max = 30)
     private String certificateType; //证件类型

     @Length(max = 100)
     private String certificateId; //证件号

     private Date effectiveStartDate; //生效日期

     private Date effectiveEndDate; //失效日期

     @Length(max = 100)
     private String bankAccount; //银行帐号

     @Length(max = 100)
     private String bankName; //银行名称

     @Length(max = 240)
     private String bankBranchName; //支行名称

     @Length(max = 4000)
     private String comments;

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setTeacherId(Long teacherId){
         this.teacherId = teacherId;
     }

     public Long getTeacherId(){
         return teacherId;
     }

     public void setTechType(String techType){
         this.techType = techType;
     }

     public String getTechType(){
         return techType;
     }

     public void setEducationType(String educationType){
         this.educationType = educationType;
     }

     public String getEducationType(){
         return educationType;
     }

     public void setEducationSchool(String educationSchool){
         this.educationSchool = educationSchool;
     }

     public String getEducationSchool(){
         return educationSchool;
     }

     public void setGradurationDate(Date gradurationDate){
         this.gradurationDate = gradurationDate;
     }

     public Date getGradurationDate(){
         return gradurationDate;
     }

     public void setTeacherNum(String teacherNum){
         this.teacherNum = teacherNum;
     }

     public String getTeacherNum(){
         return teacherNum;
     }

     public void setTeacherName(String teacherName){
         this.teacherName = teacherName;
     }

     public String getTeacherName(){
         return teacherName;
     }

     public void setBornDate(Date bornDate){
         this.bornDate = bornDate;
     }

     public Date getBornDate(){
         return bornDate;
     }

     public void setEmail(String email){
         this.email = email;
     }

     public String getEmail(){
         return email;
     }

     public void setMobile(String mobile){
         this.mobile = mobile;
     }

     public String getMobile(){
         return mobile;
     }

     public void setJoinDate(Date joinDate){
         this.joinDate = joinDate;
     }

     public Date getJoinDate(){
         return joinDate;
     }

     public void setGender(String gender){
         this.gender = gender;
     }

     public String getGender(){
         return gender;
     }

     public void setCertificateType(String certificateType){
         this.certificateType = certificateType;
     }

     public String getCertificateType(){
         return certificateType;
     }

     public void setCertificateId(String certificateId){
         this.certificateId = certificateId;
     }

     public String getCertificateId(){
         return certificateId;
     }

     public void setEffectiveStartDate(Date effectiveStartDate){
         this.effectiveStartDate = effectiveStartDate;
     }

     public Date getEffectiveStartDate(){
         return effectiveStartDate;
     }

     public void setEffectiveEndDate(Date effectiveEndDate){
         this.effectiveEndDate = effectiveEndDate;
     }

     public Date getEffectiveEndDate(){
         return effectiveEndDate;
     }

     public void setBankAccount(String bankAccount){
         this.bankAccount = bankAccount;
     }

     public String getBankAccount(){
         return bankAccount;
     }

     public void setBankName(String bankName){
         this.bankName = bankName;
     }

     public String getBankName(){
         return bankName;
     }

     public void setBankBranchName(String bankBranchName){
         this.bankBranchName = bankBranchName;
     }

     public String getBankBranchName(){
         return bankBranchName;
     }

     public void setComments(String comments){
         this.comments = comments;
     }

     public String getComments(){
         return comments;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
