package tcm.xxcse.basic.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "xxcse_attend_class_record")
public class AttendClassRecord extends BaseDTO {

     public static final String FIELD_ATTEND_ID = "attendId";
     public static final String FIELD_CLASS_STUDENT_ID = "classStudentId";
     public static final String FIELD_SCHEDULE_ID = "scheduleId";
     public static final String FIELD_START_DATETIME = "startDatetime";
     public static final String FIELD_END_DATETIME = "endDatetime";
     public static final String FIELD_SCORE = "score";
     public static final String FIELD_PERFOR_COMMENT = "perforComment";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long attendId; //表ID，主键，供其他表做外键

     private Long classStudentId;

     private Long scheduleId;

     private Date startDatetime;

     private Date endDatetime;

     private Long score;

     @Length(max = 4000)
     private String perforComment;

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setAttendId(Long attendId){
         this.attendId = attendId;
     }

     public Long getAttendId(){
         return attendId;
     }

     public void setClassStudentId(Long classStudentId){
         this.classStudentId = classStudentId;
     }

     public Long getClassStudentId(){
         return classStudentId;
     }

     public void setScheduleId(Long scheduleId){
         this.scheduleId = scheduleId;
     }

     public Long getScheduleId(){
         return scheduleId;
     }

     public void setStartDatetime(Date startDatetime){
         this.startDatetime = startDatetime;
     }

     public Date getStartDatetime(){
         return startDatetime;
     }

     public void setEndDatetime(Date endDatetime){
         this.endDatetime = endDatetime;
     }

     public Date getEndDatetime(){
         return endDatetime;
     }

     public void setScore(Long score){
         this.score = score;
     }

     public Long getScore(){
         return score;
     }

     public void setPerforComment(String perforComment){
         this.perforComment = perforComment;
     }

     public String getPerforComment(){
         return perforComment;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
