package tcm.xxcse.basic.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "xxcse_card_apply_info")
public class CardApplyInfo extends BaseDTO {

    public static final String FIELD_APPLY_ID = "applyId";
    public static final String FIELD_SCHOOL_ID = "schoolId";
    public static final String FIELD_STUDENT_ID = "studentId";
    public static final String FIELD_CARD_TYPE_CODE = "cardTypeCode";
    public static final String FIELD_OLD_CUSTOMER = "oldCustomer";
    public static final String FIELD_START_DATE = "startDate";
    public static final String FIELD_END_DATE = "endDate";
    public static final String FIELD_COMMENTS = "comments";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Id
    @GeneratedValue
    private Long applyId; //表ID，主键，供其他表做外键

    private Long schoolId; //学校

    private Long studentId; //学生

    @Length(max = 30)
    private String cardTypeCode; //办卡类型

    @Length(max = 10)
    private String oldCustomer; //是否续费

    private Date startDate; //开始日期

    private Date endDate; //结束日期

    @Length(max = 100)
    private String comments; //备注

    private Long programApplicationId;

    private Date programUpdateDate;
    @Transient
    private String studentName;
    @Transient
    private String studentNum;
    @Transient
    private Date birthday;
    @Transient
    private String schoolName;

    public String getStudentName() {
        return studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public String getStudentNum() {
        return studentNum;
    }

    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    public Long getApplyId() {
        return applyId;
    }

    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    public Long getSchoolId() {
        return schoolId;
    }

    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    public Long getStudentId() {
        return studentId;
    }

    public void setCardTypeCode(String cardTypeCode) {
        this.cardTypeCode = cardTypeCode;
    }

    public String getCardTypeCode() {
        return cardTypeCode;
    }

    public void setOldCustomer(String oldCustomer) {
        this.oldCustomer = oldCustomer;
    }

    public String getOldCustomer() {
        return oldCustomer;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getComments() {
        return comments;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
