package tcm.xxcse.basic.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "xxcse_class_schedule")
public class ClassSchedule extends BaseDTO {

     public static final String FIELD_SCHEDULE_ID = "scheduleId";
     public static final String FIELD_CLASS_ID = "classId";
     public static final String FIELD_START_DATETIME = "startDatetime";
     public static final String FIELD_END_DATETIME = "endDatetime";
     public static final String FIELD_CLASSROOM = "classroom";
     public static final String FIELD_TIME_LONG = "timeLong";
     public static final String FIELD_COMMENTS = "comments";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long scheduleId; //表ID，主键，供其他表做外键

     private Long classId;

     private Date startDatetime;

     private Date endDatetime;

     @Length(max = 100)
     private String classroom;

     private Long timeLong;

     @Length(max = 4000)
     private String comments;

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setScheduleId(Long scheduleId){
         this.scheduleId = scheduleId;
     }

     public Long getScheduleId(){
         return scheduleId;
     }

     public void setClassId(Long classId){
         this.classId = classId;
     }

     public Long getClassId(){
         return classId;
     }

     public void setStartDatetime(Date startDatetime){
         this.startDatetime = startDatetime;
     }

     public Date getStartDatetime(){
         return startDatetime;
     }

     public void setEndDatetime(Date endDatetime){
         this.endDatetime = endDatetime;
     }

     public Date getEndDatetime(){
         return endDatetime;
     }

     public void setClassroom(String classroom){
         this.classroom = classroom;
     }

     public String getClassroom(){
         return classroom;
     }

     public void setTimeLong(Long timeLong){
         this.timeLong = timeLong;
     }

     public Long getTimeLong(){
         return timeLong;
     }

     public void setComments(String comments){
         this.comments = comments;
     }

     public String getComments(){
         return comments;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
