package hap.common.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "xxfnd_pub_document_sequences")
public class PubDocumentSequences extends BaseDTO {
     @Id
     @GeneratedValue
      private Long documentSequenceId; //表ID

     @NotEmpty
      private String name;

      private String description;

      private Long applicationId;

      private String applModule; //序列所属应用模块

      private String type; //序列类型: m/a/g 人工编号/自动编号/连续编号

      private String cycType; //周期类型: month/year/always 月/年/永远

      private Long length; //序列长度

      private String inclCycPrefix; //包含周期前缀: y/n

      private String prefixChar; //字符前缀

      private String concatChar; //连接符: - / _ (前缀与序列流水号之间)

      private String enabledFlag; //启用: y/n

      private String auditTableName; //序列值历史审计表

      private Long nextSeqValue;


     public void setDocumentSequenceId(Long documentSequenceId){
         this.documentSequenceId = documentSequenceId;
     }

     public Long getDocumentSequenceId(){
         return documentSequenceId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setApplicationId(Long applicationId){
         this.applicationId = applicationId;
     }

     public Long getApplicationId(){
         return applicationId;
     }

     public void setApplModule(String applModule){
         this.applModule = applModule;
     }

     public String getApplModule(){
         return applModule;
     }

     public void setType(String type){
         this.type = type;
     }

     public String getType(){
         return type;
     }

     public void setCycType(String cycType){
         this.cycType = cycType;
     }

     public String getCycType(){
         return cycType;
     }

     public void setLength(Long length){
         this.length = length;
     }

     public Long getLength(){
         return length;
     }

     public void setInclCycPrefix(String inclCycPrefix){
         this.inclCycPrefix = inclCycPrefix;
     }

     public String getInclCycPrefix(){
         return inclCycPrefix;
     }

     public void setPrefixChar(String prefixChar){
         this.prefixChar = prefixChar;
     }

     public String getPrefixChar(){
         return prefixChar;
     }

     public void setConcatChar(String concatChar){
         this.concatChar = concatChar;
     }

     public String getConcatChar(){
         return concatChar;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setAuditTableName(String auditTableName){
         this.auditTableName = auditTableName;
     }

     public String getAuditTableName(){
         return auditTableName;
     }

     public void setNextSeqValue(Long nextSeqValue){
         this.nextSeqValue = nextSeqValue;
     }

     public Long getNextSeqValue(){
         return nextSeqValue;
     }

     }
